// apps/reactapp/src/app/app.tsx
import { useEffect } from 'react';
import { UserService } from '@elf-example/user-service';
import { useObservable } from '@ngneat/react-rxjs';

export function App() {
  const service = new UserService();
  const [ username ] = useObservable(service.repo.username$);

  useEffect(() => {
    service.getUser().subscribe();
  }, []);

  return (
    <>
      <h1>React Username = { username }</h1>
    </>
  );
}

export default App;

// apps/angularapp/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { UserService } from '@elf-example/user-service';

@Component({
  selector: 'elf-example-root',
  template: '<h1>Angular Username = {{ username$ | async }}</h1>',
})
export class AppComponent implements OnInit {

  private service = new UserService();
  username$ = this.service.repo.username$;

  ngOnInit() {
    this.service.getUser().subscribe();
  }
}
